version: '3.8'

services:
  # LSP应用（使用外部数据库）
  sponge-lsp:
    image: sponge-lsp:0.1.0
    container_name: sponge-lsp
    environment:
      # 数据库配置
      POSTGRES_DBNAME: ${POSTGRES_DBNAME:-sponge_db}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PWD: ${POSTGRES_PWD:-postgres_pwd}
      POSTGRES_HOST: ${POSTGRES_HOST:-127.0.0.1}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
    ports:
      - "12002:8000"
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped